### ISSUE TITLE
Broken links on docs.emulsify.info

### ISSUE THREAD

**Issue by kmbremner** [emulsify-ds/documentation#1]
## https://docs.emulsify.info 
> The style guide is a Gatsby theme, and instructions for installation and usage can be **found here**.

Lnks to https://github.com/emulsify-ds/gatsby-theme-emulsify

## https://docs.emulsify.info/installation/upgrading
> You may need to copy over new Emulsify styles, e.g. for  **the colors**

Links to https://github.com/emulsify-ds/emulsify-drupal/blob/drupal-fixes/components/00-base/global/01-colors/_color-vars.scss#L16-L85

**Comment by ModulesUnraveled** [comment]
Thanks! I fixed these in the docs.
