### ISSUE TITLE
FAQ Question additions

### ISSUE THREAD

**Issue by evanmwillhite** [emulsify-ds/documentation#2]
Tracking from original issue [here](https://github.com/emulsify-ds/emulsify-drupal/issues/66).

```
External/web/other fonts
Jquery
Find a good resource for webpack
```
Also referenced: https://github.com/emulsify-ds/emulsify-drupal/issues/62#issuecomment-601145472

**Comment by acouch** [comment]
I'll get started w/ jQuery and try and post something this week.

**Comment by evanmwillhite** [comment]
@acouch thank you so much! I think I just gave you write access, but let me know if you run into issues. Also, could you put this under a heading "Adding 3rd party libraries (e.g., jQuery)" - because it's actually true of any 3rd party library. The example could definitely still be jQuery cause I'm sure that will be a common one, but I want to emphasize the solution extends to others as well.

**Comment by acouch** [comment]
I've started this and will have a PR soon.

I'm wondering if you have used knobs https://github.com/storybookjs/storybook/tree/master/addons/knobs and if there are any examples. We'd like to be able to toggle different settings. I can create docs for this as I want to try and implement it this week. However wondering if this has been tackled yet or if there are any examples out there.

**Comment by acouch** [comment]
Closing this as the jQuery + 3rd party library section has been merged.
