### ISSUE TITLE
Add-ons / Knobs

### ISSUE THREAD

**Issue by acouch** [emulsify-ds/documentation#4]
I have a quick recipe for [Knobs](https://github.com/storybookjs/storybook/tree/master/addons/knobs) I can add to the docs. Could create an "Addons" section and use it as an example. Could also provide an example for "Actions" since that is available but not implemented.

┆Issue is synchronized with this [Jira Story](https://fourkitchens.atlassian.net/browse/GS-194) by [Unito](https://www.unito.io/learn-more)

**Comment by evanmwillhite** [comment]
Awesome, yes please do!

**Comment by mirzu** [comment]
Hi Aaron. We are cleaning up issues and came across this from the spring, is this something you are still planning on submitting. No problem if not, we'll just close the issue.

**Comment by evanmwillhite** [comment]
This is still a solid addition to the docs. Knobs are now called Controls, and I have examples of implementing them on a recent project, so I will incorporate those into the docs soon.

**Comment by evanmwillhite** [comment]
Oh, I had already done this 😆  https://docs.emulsify.info/usage/writing-stories#using-storybook-controls
