### ISSUE TITLE
Adding Third Parties Document Page

### ISSUE THREAD

**Issue by mctdynamic** [emulsify-ds/documentation#5]
Hi,

I am setting up Emulsify & Storybook for the first time and I think there is an error in the docs: https://docs.emulsify.info/help/3rd-party-libraries#example-use-jquery-in-a-component 

![Screen Shot 2020-05-12 at 2 27 02 PM](https://user-images.githubusercontent.com/9706682/81747309-ba329280-945c-11ea-90d6-c589683fdc58.png)

Correct me if I am wrong, but in the screenshot above, shouldn't the file be **status.twig** instead of **status.stories.js** since `{{ attach_library('THEME_NAME/status') }}` is a twig function?

**Comment by acouch** [comment]
Yes, you are correct. Thank you for noting. I have updated the documentation.
