### ISSUE TITLE
Upgrading from Deprecated Emulsify to New Documentation

### ISSUE THREAD

**Issue by cpm78** [emulsify-ds/documentation#9]
Using Upgrading from Deprecated Emulsify to New (https://docs.emulsify.info/installation/upgrading)

For Step 8 when using npm, wouldn't it need to be `npm run develop`? Running `npm develop` from within theme directory triggers no action

Our team loved the old Emulsify, and are looking forward to using this new version! Thanks for all the work you do!

┆Issue is synchronized with this [Jira Story](https://fourkitchens.atlassian.net/browse/GS-195) by [Unito](https://www.unito.io/learn-more)

**Comment by evanmwillhite** [comment]
Thanks, fixed now!
